require 'bundler/setup'
require 'rom-sql'
require 'pry'
require_relative 'lib/repositories/user_repo'
require_relative 'lib/repositories/challenge_comment_repo'
require_relative "lib/relations/users"
require_relative "lib/relations/challenge_comments"
require_relative 'lib/register_user'
require_relative 'lib/save_comment'
require_relative 'lib/rom_container'
