require 'bundler/setup'
require 'rom-sql'
require_relative 'lib/repositories/user_repo'
require_relative 'lib/repositories/challenge_comment_repo'
require 'pry'
require "#{__dir__}/lib/relations/users"
require "#{__dir__}/lib/relations/challenge_comments"
require_relative 'lib/register_user'
require_relative 'lib/save_comment'
